# <font color='yellow'> Introduction to Arrays and NumPy

An **array** is a data structure that stores an ordered collection of elements, typically of the same data type, allowing for efficient access and manipulation. 

Arrays are essential for handling large datasets and performing mathematical operations in fields such as data science, machine learning, and scientific computing. While Python’s built-in **list** can function as an array, it is not optimized for numerical tasks. 

**NumPy** is a powerful library for numerical computing in Python. It introduces the **ndarray** (N-dimensional array), which offers several advantages over Python lists:
- **Homogeneous data**: All elements in a NumPy array are of the same type (e.g., all integers or floats).
- **Multidimensional**: NumPy arrays can have one or more dimensions, making them ideal for representing vectors, matrices, and higher-dimensional data.
- **Efficient memory usage**: NumPy arrays are stored in contiguous memory locations, making them faster and more memory-efficient than Python lists.
- **Vectorized operations**: NumPy supports fast, element-wise operations on arrays without the need for explicit loops, significantly improving performance for numerical tasks.

## <font color='orange'> Key Features of NumPy:

1. **Array Creation**: NumPy allows for creating arrays from lists or other sequence-like structures, supporting both one-dimensional and multi-dimensional arrays.
2. **Indexing and Slicing**: NumPy provides efficient methods to access and modify specific elements or subarrays using indexing and slicing.
3. **Mathematical Operations**: You can perform arithmetic operations on entire arrays, including addition, subtraction, and element-wise multiplication, among others.
4. **Array Properties**: NumPy arrays have attributes to check their shape, size, and dimensionality, providing a way to understand the structure of the data.

NumPy is foundational for libraries like **Pandas** and **SciPy**, which build upon NumPy's array capabilities. 

Understanding arrays and how to manipulate them efficiently with NumPy is key for tasks in data analysis, machine learning, and scientific computing.

In [1]:
import numpy as np

### <font color='orange'> 1-D array

In [2]:
arr1d=np.array([99,102,199])

print("dimension is ", arr1d.ndim)

print("shape is ",arr1d.shape)


print(arr1d)

dimension is  1
shape is  (3,)
[ 99 102 199]


## <font color='orange'> 2-D array

In [3]:
arr2d = np.array([[89,10], [89, 13], [182,17]])

print(arr2d)

print("dimension is ", arr2d.ndim)

print("shape is ",arr2d.shape)

print(arr2d.dtype)

[[ 89  10]
 [ 89  13]
 [182  17]]
dimension is  2
shape is  (3, 2)
int64


In [ ]:
arr2d1 = np.array([[89,89,182], [10, 13,17]])

print("dimension is ", arr2d1.ndim)

print("shape is ",arr2d1.shape)

print(arr2d1.shape)

## <font color='orange'> 3-D array

In [4]:
arr3d = np.array([
                  [[44,45], [5,5]], 
                  [[43,46], [4,9]],
                  [[90,92],[7,10]]
                 ])

print("dimension is ", arr3d.ndim)

print("shape is ",arr3d.shape)

print(arr3d)

dimension is  3
shape is  (3, 2, 2)
[[[44 45]
  [ 5  5]]

 [[43 46]
  [ 4  9]]

 [[90 92]
  [ 7 10]]]


In [ ]:
arr3d1 = np.array([
                        [[44,43,90],[45,46,92]], 
                        [[5,4,7], [5,9,10]]
                    ])

print("dimension is ", arr3d1.ndim)

print("shape is ",arr3d1.shape)


print(arr3d1)

## <font color='orange'> 4-D array

In [13]:
arr4d=np.array([
                    [
                        [[18,26],[16,27],[33,57]],
                        [[25,20],[10,36],[33,59]]
                    ],
                    [
                        [[2,3],[3,1],[4,3]],
                        [[2,3],[3,6],[6,4]]
                    ]
               ])

print("dimension is ", arr4d.ndim)

print("shape is ",arr4d.shape)

print(arr4d)

dimension is  4
shape is  (2, 2, 3, 2)
[[[[18 26]
   [16 27]
   [33 57]]

  [[25 20]
   [10 36]
   [33 59]]]


 [[[ 2  3]
   [ 3  1]
   [ 4  3]]

  [[ 2  3]
   [ 3  6]
   [ 6  4]]]]


## <font color='orange'> Array subset / Indexing / Slicing

In [6]:
print(arr1d)

[ 99 102 199]


In [5]:
#[0:] start from index 0 (the first element) and include all elements up to the end of the array
#[:1] start from the beginning of the array and stop before index 1

print(arr1d[0:])
print(arr1d[1:])

print(arr1d[:1])
print(arr1d[:2])

print(arr1d[0:1])
print(arr1d[0:2])


[ 99 102 199]
[102 199]
[99]
[ 99 102]
[99]
[ 99 102]


In [8]:
print(arr3d)

[[[44 45]
  [ 5  5]]

 [[43 46]
  [ 4  9]]

 [[90 92]
  [ 7 10]]]


In [7]:
print(arr3d[1:])

[[[43 46]
  [ 4  9]]

 [[90 92]
  [ 7 10]]]


In [9]:
print(arr3d[:2])

[[[44 45]
  [ 5  5]]

 [[43 46]
  [ 4  9]]]


In [10]:
print(arr3d[1:3])

[[[43 46]
  [ 4  9]]

 [[90 92]
  [ 7 10]]]


In [11]:
print(arr3d[2][0][1])

print(arr3d[0][0][1])

print(arr3d[0][0][0])

print(arr3d[1][0][1])

92
45
44
46


In [ ]:
arr3d[1][0:]

In [ ]:
arr3d[1][0:][1:]

In [ ]:
arr3d = np.arange(60).reshape(3, 4, 5)
print(arr3d.shape)  
print(arr3d)

In [ ]:
arr3d[1][0:][1:]

In [14]:
print(arr4d)

[[[[18 26]
   [16 27]
   [33 57]]

  [[25 20]
   [10 36]
   [33 59]]]


 [[[ 2  3]
   [ 3  1]
   [ 4  3]]

  [[ 2  3]
   [ 3  6]
   [ 6  4]]]]


In [15]:
print(arr4d[0][0][0][0])
print(arr4d[1][1][2][1])

18
4


## <font color='orange'> Array Operations

In [ ]:
arr3d.ndim

In [ ]:
arr3d.shape

In [ ]:
print(arr3d.T.shape)
print(arr3d.T)

## <font color='orange'> Vector and 1-D array

A 1D NumPy array (vector) is an ordered collection of numbers. It is created using np.array() and is used to represent vectors in mathematical operations. In NumPy, vectors can be manipulated using a variety of arithmetic and linear algebra operations.

This can be thought of as a matrix with either one row or one column

### <font color='pink'> Operations

1. Addition: Adds two vectors element-wise.

1. Subtraction: Subtracts two vectors element-wise.

1. Element-wise Multiplication: Multiplies two vectors element-wise.

1. Element-wise Division: Divides two vectors element-wise.

1. Dot Product of two vectors: Computes the dot product of two vectors.

1. Scalar Multiplication: Multiplies each element of a vector by a scalar.

1. Element-wise Power: Raises each element of the vector to a specified power.

1. Sum of Elements: Computes the sum of all elements in the vector.

1. Magnitude (Norm) of a vector: Computes the magnitude (Euclidean norm) of the vector. (using linalg)

**Norm and dot product are related if applied for the same vector, square of norm is the dot product**

In [17]:
arr1d=np.array([2,4,7])
arr1d_1=np.array([10,12,28])

In [18]:
print(arr1d.ndim)
print(arr1d_1.ndim)

1
1


In [19]:
print(arr1d)

[2 4 7]


In [21]:
print(arr1d_1)

[10 12 28]


In [20]:
print(arr1d + 2)

print(arr1d **2)

print(arr1d*arr1d)

print(arr1d**arr1d)

print(arr1d*arr1d+2)

print(arr1d_1/arr1d)

print(arr1d_1*arr1d)

[4 6 9]
[ 4 16 49]
[ 4 16 49]
[     4    256 823543]
[ 6 18 51]
[5. 3. 4.]
[ 20  48 196]


In [22]:
print(np.dot(arr1d_1,arr1d_1)) 
100+144+(28**2)

1028


1028

In [ ]:
print(np.dot(arr1d,arr1d)) 
print(np.dot(arr1d,arr1d_1)) 

In [23]:
print(np.sum(arr1d))

13


In [24]:
print(np.linalg.norm(arr1d))

8.306623862918075


In [25]:
print(np.linalg.norm(arr1d)**2)
print(69**0.5)

69.0
8.306623862918075


In [26]:
print(np.dot(arr1d,arr1d)) 

69


## <font color='orange'> Matrix and 2-D Array

NumPy arrays are highly useful for representing matrices and performing matrix operations in Python. 

NumPy provides many features that make it easy to work with matrices (which are essentially 2D arrays) and perform common mathematical operations, such as 

1. matrix addition / subtraction
2. matrix multiplication
3. element-wise operations
4. other linear algebra tasks (inverse / transpose / determinant etc)

In [27]:
# 3 x 2 matrix
arr2dM = np.array([[8,10], [9, 13], [12,17]])
arr2dM

array([[ 8, 10],
       [ 9, 13],
       [12, 17]])

In [28]:
print("Matrix Addition")
print(arr2dM+2)

print("Scalar / constant multiplication")
print(arr2dM * 2)

print("Matrix transpose")
print(arr2dM . T)

print("Element wise exponentiation")
print(arr2dM ** 2)

print("Matrix multiplication") #dot product
print(np.dot(arr2dM , arr2dM.T))

print("norm")
print(np.linalg.norm(arr2dM))

Matrix Addition
[[10 12]
 [11 15]
 [14 19]]
Scalar / constant multiplication
[[16 20]
 [18 26]
 [24 34]]
Matrix transpose
[[ 8  9 12]
 [10 13 17]]
Element wise exponentiation
[[ 64 100]
 [ 81 169]
 [144 289]]
Matrix multiplication
[[164 202 266]
 [202 250 329]
 [266 329 433]]
norm
29.103264421710495


In [ ]:
mat3=np.array([[1,2,3],[3,4,5],[5,6,7]]) #a square matrix

In [ ]:
np. diagonal(arr2dM)

In [ ]:
np. diagonal(mat3)

In [ ]:
print(np.trace(mat3))
print(np.trace(arr2dM))

In [ ]:
print(mat3)
print(np.multiply(mat3,mat3))
print(np.dot(mat3,mat3))

In [ ]:
print(np.linalg.inv(mat3))

In [ ]:
np.linalg.det(mat3)

In [126]:
mat3.shape

(3, 3)

In [125]:
np.matmul(mat3,mat3)

array([[22, 28, 34],
       [40, 52, 64],
       [58, 76, 94]])

In [ ]:
np.linalg.eig(mat3.T)